#cloud-config
hostname: netbox-auto
manage_etc_hosts: true
users:
  - name: user
    gecos: User
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    passwd: $6$YD8WbS.EhZFlfAvE$b9BwbfMEQJiNztZmhFsNY7hUP86W.Ao6.fi2SJ3CcO9ijfEClA2ABI4tOQjinvCtOynvvSZxWoDGuTLy2n59s0
    lock_passwd: false
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    permissions: '0600'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp1s0:
            dhcp4: false
            addresses:
              - 10.2.100.5/24
            routes:
            - to: default
              via: 10.2.100.1
            nameservers:
              addresses: [8.8.8.8]

runcmd:
  - [ netplan, apply ]
package_update: true
package_upgrade: true
packages:
  - git
  - ansible
  - python3-pip
ansible:
  install_method: pip
  package_name: ansible
  run_user: root
  setup_controller:
    repositories:
      - path: /tmp/ansible/
        source: "https://github.com/The-Cave-Tech/netbox-ansible-cloud-init.git"
    run_ansible:
      - playbook_dir: /tmp/ansible/ansible
        playbook_name: playbooks/netbox.yaml