---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kea DHCP server
  ansible.builtin.apt:
    name: kea
    state: present

- name: Set kea-ctrl-agent password
  ansible.builtin.copy:
    content: "{{ kea_ctrl_agent_password }}"
    dest: /etc/kea/kea-api-password
    owner: root
    group: _kea
    mode: '0640'
  register: password_file

- name: Configure Kea DHCP REST API
  ansible.builtin.blockinfile:
    path: /etc/kea/kea-ctrl-agent.conf
    block: |
      "Control-agent": {
        "http-host": "127.0.0.1",
        "http-port": 8000,
        "control-sockets": {
          "dhcp4": {
            "socket-type": "unix",
            "socket-name": "/tmp/kea-dhcp4-ctrl.sock"
          }
        }
      }


- name: Reconfigure kea-ctrl-agent if password changed
  ansible.builtin.command:
    cmd: dpkg-reconfigure kea-ctrl-agent
  when: password_file.changed

- name: Restart Kea service
  ansible.builtin.systemd:
    name: kea-ctrl-agent.service
    state: restarted