---
- name: Run system roles on all nodes
  hosts: all
  become: yes
  roles:
    - network_config

# - name: Run netbox role on all netbox-nodes
#   hosts: netbox_nodes
#   become: yes
#   roles:
#     - network_config
#     - netbox
#     - netbox_device_types
