---
- name: Deploy MicroCeph cluster
  hosts: microceph
  become: yes
  roles:
    - role: microceph

- name: Deploy Microk8s cluster
  hosts: microk8s
  become: yes
  roles:
    - role: microk8s
      vars: 
        dashboard_ingress_host: "dashboard.netbox.local"
