---
- name: Clone Device-Type-Library-Import repository
  git:
    repo: 'https://github.com/netbox-community/Device-Type-Library-Import.git'
    dest: '/tmp/device-type-library-import'
    clone: yes
    update: yes

- name: Install requirements using pip
  pip:
    requirements: '/tmp/device-type-library-import/Device-Type-Library-Import/requirements.txt'
    virtualenv: '/tmp/device-type-library-import/Device-Type-Library-Import'

- name: Copy .env.example to .env
  copy:
    src: '/tmp/device-type-library-import/Device-Type-Library-Import/.env.example'
    dest: '/tmp/device-type-library-import/Device-Type-Library-Import/.env'

- name: Run the import script
  command: './nb-dt-import.py'
  args:
    chdir: '/tmp/device-type-library-import/Device-Type-Library-Import'
    executable: '/bin/bash'
  environment:
    PATH: "{{ ansible_env.PATH }}:/tmp/device-type-library-import/Device-Type-Library-Import"
