---

# Add the official Python repository
- name: Add deadsnakes PPA
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present

# Download and install the latest version of Python and Pip3 from the official python repos
- name: Install Python3 and Pip3
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python3-kubernetes

# - name: Set Python alternatives
#   ansible.builtin.shell:
#     cmd: update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# - name: Set Python3 alternatives
#   ansible.builtin.shell:
#     cmd: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3 1

# - name: Set Pip alternatives
#   ansible.builtin.shell:
#     cmd: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
      
# - name: Set Pip3 alternatives
#   ansible.builtin.shell:
#     cmd: update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3 1
