all:
  hosts:
    node1.netbox.local:
    node2.netbox.local:
    node3.netbox.local:
  children:
    netbox_nodes:
      hosts:
        node1.netbox.local:
        node2.netbox.local:
        node3.netbox.local:
    microceph:
      hosts:
        node1.netbox.local:
        node2.netbox.local:
        node3.netbox.local:
    microk8s:
      hosts:
        node1.netbox.local:
        node2.netbox.local:
        node3.netbox.local:
  vars:
    ansible_ssh_private_key_file: /etc/ssh/ssh_host_ed25519_key
    ansible_user: user