---
# tasks file for postgresql
- name: Add the CNPG.io Helm repository
  kubernetes.core.helm_repository:
    name: cnpg
    repo_url: "https://cloudnative-pg.github.io/charts"
    state: present

- name: Install the CNPG operator 
  kubernetes.core.helm:
    name: cnpg
    chart_ref: "cnpg/cloudnative-pg"
    release_namespace: cnpg-system
    create_namespace: true

- name: Create a values.yaml file
  template:
    src: values.yaml.j2
    dest: "/tmp/values.yaml"

- name: Install PostgreSQL
  kubernetes.core.helm:
    name: postgres
    chart_ref: "cnpg/cluster"
    release_namespace: postgres
    create_namespace: true
    values_files:
      - "/tmp/values.yaml"
