---
# tasks file for postgresql
- name: Add the CNPG.io Helm repository
  kubernetes.core.helm_repository:
    name: cnpg
    repo_url: "https://cloudnative-pg.github.io/charts"
    state: present

- name: Install the CNPG operator 
  kubernetes.core.helm:
    name: cnpg
    chart_ref: "cnpg/cloudnative-pg"
    release_namespace: cnpg-system
    create_namespace: true

- name: Wait until operator deployment has at least one available replica
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: cnpg-system
    name: cnpg-cloudnative-pg
  register: deployment_status
  until: deployment_status.resources is defined and 
    deployment_status.resources | length > 0 and
    deployment_status.resources[0].status is defined and
    deployment_status.resources[0].status.availableReplicas is defined and
    deployment_status.resources[0].status.availableReplicas >= 1
  retries: 10
  delay: 10

- name: Create a values.yaml file
  template:
    src: values.yaml.j2
    dest: "/tmp/values.yaml"

- name: Install PostgreSQL
  kubernetes.core.helm:
    name: postgres
    chart_ref: "cnpg/cluster"
    release_namespace: postgres
    create_namespace: true
    values_files:
      - "/tmp/values.yaml"
